[package]
name = "exec-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = { version = "=0.20.0-rc.3", features = ["rustls-tls"], default-features = false }

[patch.crates-io]
ring = { git = 'https://github.com/tvquizphd/ring', branch = "cosmo" }
mio = { git = 'https://github.com/tvquizphd/mio', branch = "cosmo-notgull" }
socket2 = { git = 'https://github.com/tvquizphd/socket2', branch = "cosmo" }
tokio = { git = 'https://github.com/tvquizphd/tokio', branch = "as-fd" }
